# Generated by Django 3.0.4 on 2021-01-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='sdddddddddddd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='dddddddd', upload_to='upload_locatio'),
            preserve_default=False,
        ),
    ]
